# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Magisterio/IPD-432/Tarea_4/ipd432_tarea_4/soc/vivado/coprocessor_32_float/coprocessor_32_float.srcs/sources_1/bd/design_1/ip/design_1_eucDis32_float_0_1/design_1_eucDis32_float_0_1.xci
# IP: The module: 'design_1_eucDis32_float_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Magisterio/IPD-432/Tarea_4/ipd432_tarea_4/soc/vivado/coprocessor_32_float/coprocessor_32_float.gen/sources_1/bd/design_1/ip/design_1_eucDis32_float_0_1/constraints/eucDis32_float_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_eucDis32_float_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/Magisterio/IPD-432/Tarea_4/ipd432_tarea_4/soc/vivado/coprocessor_32_float/coprocessor_32_float.srcs/sources_1/bd/design_1/ip/design_1_eucDis32_float_0_1/design_1_eucDis32_float_0_1.xci
# IP: The module: 'design_1_eucDis32_float_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Magisterio/IPD-432/Tarea_4/ipd432_tarea_4/soc/vivado/coprocessor_32_float/coprocessor_32_float.gen/sources_1/bd/design_1/ip/design_1_eucDis32_float_0_1/constraints/eucDis32_float_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_eucDis32_float_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
