// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module eucDis_sqrt_fixed_33_33_s (
        ap_clk,
        ap_rst,
        x,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [26:0] x;
output  [16:0] ap_return;

wire   [35:0] x_l_I_V_32_fu_334_p3;
reg   [35:0] x_l_I_V_32_reg_1458;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_pp0_stage0_11001;
wire   [16:0] res_I_V_31_fu_342_p3;
reg   [16:0] res_I_V_31_reg_1464;
wire   [0:0] icmp_ln443_1_fu_382_p2;
reg   [0:0] icmp_ln443_1_reg_1470;
wire   [5:0] sub_ln212_1_fu_388_p2;
reg   [5:0] sub_ln212_1_reg_1476;
wire   [35:0] x_l_I_V_34_fu_491_p3;
reg   [35:0] x_l_I_V_34_reg_1481;
wire   [16:0] res_I_V_33_fu_499_p3;
reg   [16:0] res_I_V_33_reg_1487;
wire   [0:0] icmp_ln443_3_fu_539_p2;
reg   [0:0] icmp_ln443_3_reg_1493;
wire   [7:0] sub_ln212_3_fu_545_p2;
reg   [7:0] sub_ln212_3_reg_1499;
wire   [35:0] x_l_I_V_fu_648_p3;
reg   [35:0] x_l_I_V_reg_1504;
wire   [16:0] res_I_V_35_fu_656_p3;
reg   [16:0] res_I_V_35_reg_1510;
wire   [0:0] icmp_ln443_5_fu_696_p2;
reg   [0:0] icmp_ln443_5_reg_1516;
wire   [9:0] sub_ln212_5_fu_702_p2;
reg   [9:0] sub_ln212_5_reg_1522;
wire   [35:0] x_l_I_V_37_fu_805_p3;
reg   [35:0] x_l_I_V_37_reg_1527;
wire   [16:0] res_I_V_36_fu_813_p3;
reg   [16:0] res_I_V_36_reg_1533;
wire   [0:0] icmp_ln443_7_fu_853_p2;
reg   [0:0] icmp_ln443_7_reg_1539;
wire   [11:0] sub_ln212_7_fu_859_p2;
reg   [11:0] sub_ln212_7_reg_1545;
wire   [35:0] x_l_I_V_39_fu_962_p3;
reg   [35:0] x_l_I_V_39_reg_1550;
wire   [16:0] res_I_V_38_fu_970_p3;
reg   [16:0] res_I_V_38_reg_1556;
wire   [0:0] icmp_ln443_9_fu_1010_p2;
reg   [0:0] icmp_ln443_9_reg_1562;
wire   [13:0] sub_ln212_9_fu_1016_p2;
reg   [13:0] sub_ln212_9_reg_1568;
wire   [35:0] x_l_I_V_41_fu_1119_p3;
reg   [35:0] x_l_I_V_41_reg_1573;
wire   [16:0] res_I_V_40_fu_1127_p3;
reg   [16:0] res_I_V_40_reg_1579;
wire   [0:0] icmp_ln443_11_fu_1167_p2;
reg   [0:0] icmp_ln443_11_reg_1585;
wire   [15:0] sub_ln212_11_fu_1173_p2;
reg   [15:0] sub_ln212_11_reg_1591;
wire   [35:0] x_l_I_V_42_fu_1198_p3;
reg   [35:0] x_l_I_V_42_reg_1596;
wire   [0:0] icmp_ln443_12_fu_1242_p2;
reg   [0:0] icmp_ln443_12_reg_1602;
wire   [16:0] sub_ln212_12_fu_1248_p2;
reg   [16:0] sub_ln212_12_reg_1607;
wire   [16:0] res_I_V_42_fu_1264_p3;
reg   [16:0] res_I_V_42_reg_1612;
reg   [15:0] p_Result_39_reg_1618;
wire   [35:0] x_l_I_V_44_fu_1352_p3;
reg   [35:0] x_l_I_V_44_reg_1623;
wire   [16:0] res_I_V_43_fu_1360_p3;
reg   [16:0] res_I_V_43_reg_1629;
wire   [0:0] icmp_ln443_14_fu_1383_p2;
reg   [0:0] icmp_ln443_14_reg_1635;
wire   [18:0] sub_ln212_14_fu_1389_p2;
reg   [18:0] sub_ln212_14_reg_1641;
wire  signed [26:0] sext_ln666_fu_218_p0;
wire    ap_block_pp0_stage0;
wire  signed [31:0] sext_ln666_fu_218_p1;
wire  signed [26:0] tmp_fu_226_p1;
wire   [0:0] tmp_fu_226_p3;
wire   [35:0] zext_ln666_fu_222_p1;
wire   [3:0] select_ln277_fu_234_p3;
wire   [35:0] p_Result_48_fu_242_p5;
wire   [1:0] select_ln443_fu_270_p3;
wire   [35:0] x_l_I_V_31_fu_254_p3;
wire   [2:0] tmp_2_fu_278_p3;
wire   [4:0] p_Result_49_fu_286_p4;
wire   [4:0] zext_ln443_fu_296_p1;
wire   [4:0] sub_ln212_fu_306_p2;
wire   [16:0] select_ln239_fu_262_p3;
wire   [0:0] icmp_ln443_fu_300_p2;
wire   [35:0] p_Result_50_fu_312_p5;
wire   [16:0] p_Result_51_fu_324_p4;
wire   [3:0] p_Result_8_fu_350_p4;
wire   [4:0] tmp_3_fu_360_p3;
wire   [5:0] p_Result_52_fu_368_p4;
wire   [5:0] zext_ln443_1_fu_378_p1;
wire   [35:0] p_Result_53_fu_394_p5;
wire   [16:0] p_Result_54_fu_404_p4;
wire   [16:0] res_I_V_32_fu_419_p3;
wire   [4:0] p_Result_s_fu_425_p4;
wire   [35:0] x_l_I_V_33_fu_413_p3;
wire   [5:0] tmp_4_fu_435_p3;
wire   [6:0] p_Result_55_fu_443_p4;
wire   [6:0] zext_ln443_2_fu_453_p1;
wire   [6:0] sub_ln212_2_fu_463_p2;
wire   [0:0] icmp_ln443_2_fu_457_p2;
wire   [35:0] p_Result_56_fu_469_p5;
wire   [16:0] p_Result_57_fu_481_p4;
wire   [5:0] p_Result_5_fu_507_p4;
wire   [6:0] tmp_5_fu_517_p3;
wire   [7:0] p_Result_58_fu_525_p4;
wire   [7:0] zext_ln443_3_fu_535_p1;
wire   [35:0] p_Result_59_fu_551_p5;
wire   [16:0] p_Result_60_fu_561_p4;
wire   [16:0] res_I_V_34_fu_576_p3;
wire   [6:0] p_Result_10_fu_582_p4;
wire   [35:0] x_l_I_V_35_fu_570_p3;
wire   [7:0] tmp_6_fu_592_p3;
wire   [8:0] p_Result_61_fu_600_p4;
wire   [8:0] zext_ln443_4_fu_610_p1;
wire   [8:0] sub_ln212_4_fu_620_p2;
wire   [0:0] icmp_ln443_4_fu_614_p2;
wire   [35:0] p_Result_62_fu_626_p5;
wire   [16:0] p_Result_63_fu_638_p4;
wire   [7:0] p_Result_14_fu_664_p4;
wire   [8:0] tmp_7_fu_674_p3;
wire   [9:0] p_Result_64_fu_682_p4;
wire   [9:0] zext_ln443_5_fu_692_p1;
wire   [35:0] p_Result_65_fu_708_p5;
wire   [16:0] p_Result_66_fu_718_p4;
wire   [16:0] res_I_V_fu_733_p3;
wire   [8:0] p_Result_18_fu_739_p4;
wire   [35:0] x_l_I_V_36_fu_727_p3;
wire   [9:0] tmp_8_fu_749_p3;
wire   [10:0] p_Result_67_fu_757_p4;
wire   [10:0] zext_ln443_6_fu_767_p1;
wire   [10:0] sub_ln212_6_fu_777_p2;
wire   [0:0] icmp_ln443_6_fu_771_p2;
wire   [35:0] p_Result_68_fu_783_p5;
wire   [16:0] p_Result_69_fu_795_p4;
wire   [9:0] p_Result_21_fu_821_p4;
wire   [10:0] tmp_9_fu_831_p3;
wire   [11:0] p_Result_70_fu_839_p4;
wire   [11:0] zext_ln443_7_fu_849_p1;
wire   [35:0] p_Result_71_fu_865_p5;
wire   [16:0] p_Result_72_fu_875_p4;
wire   [16:0] res_I_V_37_fu_890_p3;
wire   [10:0] p_Result_24_fu_896_p4;
wire   [35:0] x_l_I_V_38_fu_884_p3;
wire   [11:0] tmp_s_fu_906_p3;
wire   [12:0] p_Result_73_fu_914_p4;
wire   [12:0] zext_ln443_8_fu_924_p1;
wire   [12:0] sub_ln212_8_fu_934_p2;
wire   [0:0] icmp_ln443_8_fu_928_p2;
wire   [35:0] p_Result_74_fu_940_p5;
wire   [16:0] p_Result_75_fu_952_p4;
wire   [11:0] p_Result_27_fu_978_p4;
wire   [12:0] tmp_1_fu_988_p3;
wire   [13:0] p_Result_76_fu_996_p4;
wire   [13:0] zext_ln443_9_fu_1006_p1;
wire   [35:0] p_Result_77_fu_1022_p5;
wire   [16:0] p_Result_78_fu_1032_p4;
wire   [16:0] res_I_V_39_fu_1047_p3;
wire   [12:0] p_Result_30_fu_1053_p4;
wire   [35:0] x_l_I_V_40_fu_1041_p3;
wire   [13:0] tmp_10_fu_1063_p3;
wire   [14:0] p_Result_79_fu_1071_p4;
wire   [14:0] zext_ln443_10_fu_1081_p1;
wire   [14:0] sub_ln212_10_fu_1091_p2;
wire   [0:0] icmp_ln443_10_fu_1085_p2;
wire   [35:0] p_Result_80_fu_1097_p5;
wire   [16:0] p_Result_81_fu_1109_p4;
wire   [13:0] p_Result_33_fu_1135_p4;
wire   [14:0] tmp_11_fu_1145_p3;
wire   [15:0] p_Result_82_fu_1153_p4;
wire   [15:0] zext_ln443_11_fu_1163_p1;
wire   [35:0] p_Result_83_fu_1179_p5;
wire   [16:0] p_Result_84_fu_1189_p4;
wire   [16:0] res_I_V_41_fu_1204_p3;
wire   [14:0] p_Result_36_fu_1210_p4;
wire   [15:0] tmp_12_fu_1220_p3;
wire   [16:0] p_Result_85_fu_1228_p4;
wire   [16:0] zext_ln443_12_fu_1238_p1;
wire   [16:0] p_Result_87_fu_1254_p4;
wire   [35:0] p_Result_86_fu_1282_p5;
wire   [35:0] x_l_I_V_43_fu_1292_p3;
wire   [16:0] tmp_13_fu_1298_p3;
wire   [17:0] p_Result_88_fu_1305_p4;
wire   [17:0] zext_ln443_13_fu_1315_p1;
wire   [17:0] sub_ln212_13_fu_1325_p2;
wire   [0:0] icmp_ln443_13_fu_1319_p2;
wire   [35:0] p_Result_89_fu_1331_p5;
wire   [16:0] p_Result_90_fu_1343_p4;
wire   [17:0] tmp_14_fu_1367_p3;
wire   [18:0] p_Result_91_fu_1375_p1;
wire   [18:0] zext_ln443_14_fu_1379_p1;
wire   [35:0] p_Result_92_fu_1395_p5;
wire   [16:0] p_Result_93_fu_1405_p4;
wire   [16:0] res_I_V_44_fu_1420_p3;
wire   [33:0] mul_I_V_fu_1426_p3;
wire   [35:0] x_l_I_V_45_fu_1414_p3;
wire   [35:0] zext_ln671_fu_1434_p1;
wire   [0:0] p_Result_s_60_fu_1438_p2;
wire   [16:0] res_I_V_29_fu_1444_p2;
reg   [26:0] x_int_reg;
wire    ap_ce_reg;

always @ (posedge ap_clk) begin
    x_int_reg <= x;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln443_11_reg_1585 <= icmp_ln443_11_fu_1167_p2;
        icmp_ln443_12_reg_1602 <= icmp_ln443_12_fu_1242_p2;
        icmp_ln443_14_reg_1635 <= icmp_ln443_14_fu_1383_p2;
        icmp_ln443_1_reg_1470 <= icmp_ln443_1_fu_382_p2;
        icmp_ln443_3_reg_1493 <= icmp_ln443_3_fu_539_p2;
        icmp_ln443_5_reg_1516 <= icmp_ln443_5_fu_696_p2;
        icmp_ln443_7_reg_1539 <= icmp_ln443_7_fu_853_p2;
        icmp_ln443_9_reg_1562 <= icmp_ln443_9_fu_1010_p2;
        p_Result_39_reg_1618 <= {{res_I_V_42_fu_1264_p3[16:1]}};
        res_I_V_31_reg_1464 <= res_I_V_31_fu_342_p3;
        res_I_V_33_reg_1487 <= res_I_V_33_fu_499_p3;
        res_I_V_35_reg_1510 <= res_I_V_35_fu_656_p3;
        res_I_V_36_reg_1533 <= res_I_V_36_fu_813_p3;
        res_I_V_38_reg_1556 <= res_I_V_38_fu_970_p3;
        res_I_V_40_reg_1579 <= res_I_V_40_fu_1127_p3;
        res_I_V_42_reg_1612 <= res_I_V_42_fu_1264_p3;
        res_I_V_43_reg_1629 <= res_I_V_43_fu_1360_p3;
        sub_ln212_11_reg_1591 <= sub_ln212_11_fu_1173_p2;
        sub_ln212_12_reg_1607 <= sub_ln212_12_fu_1248_p2;
        sub_ln212_14_reg_1641 <= sub_ln212_14_fu_1389_p2;
        sub_ln212_1_reg_1476 <= sub_ln212_1_fu_388_p2;
        sub_ln212_3_reg_1499 <= sub_ln212_3_fu_545_p2;
        sub_ln212_5_reg_1522 <= sub_ln212_5_fu_702_p2;
        sub_ln212_7_reg_1545 <= sub_ln212_7_fu_859_p2;
        sub_ln212_9_reg_1568 <= sub_ln212_9_fu_1016_p2;
        x_l_I_V_32_reg_1458 <= x_l_I_V_32_fu_334_p3;
        x_l_I_V_34_reg_1481 <= x_l_I_V_34_fu_491_p3;
        x_l_I_V_37_reg_1527 <= x_l_I_V_37_fu_805_p3;
        x_l_I_V_39_reg_1550 <= x_l_I_V_39_fu_962_p3;
        x_l_I_V_41_reg_1573 <= x_l_I_V_41_fu_1119_p3;
        x_l_I_V_42_reg_1596 <= x_l_I_V_42_fu_1198_p3;
        x_l_I_V_44_reg_1623 <= x_l_I_V_44_fu_1352_p3;
        x_l_I_V_reg_1504 <= x_l_I_V_fu_648_p3;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_return = ((p_Result_s_60_fu_1438_p2[0:0] == 1'b1) ? res_I_V_29_fu_1444_p2 : res_I_V_44_fu_1420_p3);

assign icmp_ln443_10_fu_1085_p2 = ((p_Result_79_fu_1071_p4 < zext_ln443_10_fu_1081_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_11_fu_1167_p2 = ((p_Result_82_fu_1153_p4 < zext_ln443_11_fu_1163_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_12_fu_1242_p2 = ((p_Result_85_fu_1228_p4 < zext_ln443_12_fu_1238_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_13_fu_1319_p2 = ((p_Result_88_fu_1305_p4 < zext_ln443_13_fu_1315_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_14_fu_1383_p2 = ((p_Result_91_fu_1375_p1 < zext_ln443_14_fu_1379_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_1_fu_382_p2 = ((p_Result_52_fu_368_p4 < zext_ln443_1_fu_378_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_2_fu_457_p2 = ((p_Result_55_fu_443_p4 < zext_ln443_2_fu_453_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_3_fu_539_p2 = ((p_Result_58_fu_525_p4 < zext_ln443_3_fu_535_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_4_fu_614_p2 = ((p_Result_61_fu_600_p4 < zext_ln443_4_fu_610_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_5_fu_696_p2 = ((p_Result_64_fu_682_p4 < zext_ln443_5_fu_692_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_6_fu_771_p2 = ((p_Result_67_fu_757_p4 < zext_ln443_6_fu_767_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_7_fu_853_p2 = ((p_Result_70_fu_839_p4 < zext_ln443_7_fu_849_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_8_fu_928_p2 = ((p_Result_73_fu_914_p4 < zext_ln443_8_fu_924_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_9_fu_1010_p2 = ((p_Result_76_fu_996_p4 < zext_ln443_9_fu_1006_p1) ? 1'b1 : 1'b0);

assign icmp_ln443_fu_300_p2 = ((p_Result_49_fu_286_p4 < zext_ln443_fu_296_p1) ? 1'b1 : 1'b0);

assign mul_I_V_fu_1426_p3 = {{17'd0}, {res_I_V_44_fu_1420_p3}};

assign p_Result_10_fu_582_p4 = {{res_I_V_34_fu_576_p3[16:10]}};

assign p_Result_14_fu_664_p4 = {{res_I_V_35_fu_656_p3[16:9]}};

assign p_Result_18_fu_739_p4 = {{res_I_V_fu_733_p3[16:8]}};

assign p_Result_21_fu_821_p4 = {{res_I_V_36_fu_813_p3[16:7]}};

assign p_Result_24_fu_896_p4 = {{res_I_V_37_fu_890_p3[16:6]}};

assign p_Result_27_fu_978_p4 = {{res_I_V_38_fu_970_p3[16:5]}};

assign p_Result_30_fu_1053_p4 = {{res_I_V_39_fu_1047_p3[16:4]}};

assign p_Result_33_fu_1135_p4 = {{res_I_V_40_fu_1127_p3[16:3]}};

assign p_Result_36_fu_1210_p4 = {{res_I_V_41_fu_1204_p3[16:2]}};

assign p_Result_48_fu_242_p5 = {{zext_ln666_fu_222_p1[35:34]}, {select_ln277_fu_234_p3}, {zext_ln666_fu_222_p1[29:0]}};

assign p_Result_49_fu_286_p4 = {{x_l_I_V_31_fu_254_p3[32:28]}};

assign p_Result_50_fu_312_p5 = {{x_l_I_V_31_fu_254_p3[35:33]}, {sub_ln212_fu_306_p2}, {x_l_I_V_31_fu_254_p3[27:0]}};

assign p_Result_51_fu_324_p4 = {select_ln239_fu_262_p3[17 - 1:15], |(1'd1), select_ln239_fu_262_p3[13:0]};

assign p_Result_52_fu_368_p4 = {{x_l_I_V_32_fu_334_p3[31:26]}};

assign p_Result_53_fu_394_p5 = {{x_l_I_V_32_reg_1458[35:32]}, {sub_ln212_1_reg_1476}, {x_l_I_V_32_reg_1458[25:0]}};

assign p_Result_54_fu_404_p4 = {res_I_V_31_reg_1464[17 - 1:14], |(1'd1), res_I_V_31_reg_1464[12:0]};

assign p_Result_55_fu_443_p4 = {{x_l_I_V_33_fu_413_p3[30:24]}};

assign p_Result_56_fu_469_p5 = {{x_l_I_V_33_fu_413_p3[35:31]}, {sub_ln212_2_fu_463_p2}, {x_l_I_V_33_fu_413_p3[23:0]}};

assign p_Result_57_fu_481_p4 = {res_I_V_32_fu_419_p3[17 - 1:13], |(1'd1), res_I_V_32_fu_419_p3[11:0]};

assign p_Result_58_fu_525_p4 = {{x_l_I_V_34_fu_491_p3[29:22]}};

assign p_Result_59_fu_551_p5 = {{x_l_I_V_34_reg_1481[35:30]}, {sub_ln212_3_reg_1499}, {x_l_I_V_34_reg_1481[21:0]}};

assign p_Result_5_fu_507_p4 = {{res_I_V_33_fu_499_p3[16:11]}};

assign p_Result_60_fu_561_p4 = {res_I_V_33_reg_1487[17 - 1:12], |(1'd1), res_I_V_33_reg_1487[10:0]};

assign p_Result_61_fu_600_p4 = {{x_l_I_V_35_fu_570_p3[28:20]}};

assign p_Result_62_fu_626_p5 = {{x_l_I_V_35_fu_570_p3[35:29]}, {sub_ln212_4_fu_620_p2}, {x_l_I_V_35_fu_570_p3[19:0]}};

assign p_Result_63_fu_638_p4 = {res_I_V_34_fu_576_p3[17 - 1:11], |(1'd1), res_I_V_34_fu_576_p3[9:0]};

assign p_Result_64_fu_682_p4 = {{x_l_I_V_fu_648_p3[27:18]}};

assign p_Result_65_fu_708_p5 = {{x_l_I_V_reg_1504[35:28]}, {sub_ln212_5_reg_1522}, {x_l_I_V_reg_1504[17:0]}};

assign p_Result_66_fu_718_p4 = {res_I_V_35_reg_1510[17 - 1:10], |(1'd1), res_I_V_35_reg_1510[8:0]};

assign p_Result_67_fu_757_p4 = {{x_l_I_V_36_fu_727_p3[26:16]}};

assign p_Result_68_fu_783_p5 = {{x_l_I_V_36_fu_727_p3[35:27]}, {sub_ln212_6_fu_777_p2}, {x_l_I_V_36_fu_727_p3[15:0]}};

assign p_Result_69_fu_795_p4 = {res_I_V_fu_733_p3[17 - 1:9], |(1'd1), res_I_V_fu_733_p3[7:0]};

assign p_Result_70_fu_839_p4 = {{x_l_I_V_37_fu_805_p3[25:14]}};

assign p_Result_71_fu_865_p5 = {{x_l_I_V_37_reg_1527[35:26]}, {sub_ln212_7_reg_1545}, {x_l_I_V_37_reg_1527[13:0]}};

assign p_Result_72_fu_875_p4 = {res_I_V_36_reg_1533[17 - 1:8], |(1'd1), res_I_V_36_reg_1533[6:0]};

assign p_Result_73_fu_914_p4 = {{x_l_I_V_38_fu_884_p3[24:12]}};

assign p_Result_74_fu_940_p5 = {{x_l_I_V_38_fu_884_p3[35:25]}, {sub_ln212_8_fu_934_p2}, {x_l_I_V_38_fu_884_p3[11:0]}};

assign p_Result_75_fu_952_p4 = {res_I_V_37_fu_890_p3[17 - 1:7], |(1'd1), res_I_V_37_fu_890_p3[5:0]};

assign p_Result_76_fu_996_p4 = {{x_l_I_V_39_fu_962_p3[23:10]}};

assign p_Result_77_fu_1022_p5 = {{x_l_I_V_39_reg_1550[35:24]}, {sub_ln212_9_reg_1568}, {x_l_I_V_39_reg_1550[9:0]}};

assign p_Result_78_fu_1032_p4 = {res_I_V_38_reg_1556[17 - 1:6], |(1'd1), res_I_V_38_reg_1556[4:0]};

assign p_Result_79_fu_1071_p4 = {{x_l_I_V_40_fu_1041_p3[22:8]}};

assign p_Result_80_fu_1097_p5 = {{x_l_I_V_40_fu_1041_p3[35:23]}, {sub_ln212_10_fu_1091_p2}, {x_l_I_V_40_fu_1041_p3[7:0]}};

assign p_Result_81_fu_1109_p4 = {res_I_V_39_fu_1047_p3[17 - 1:5], |(1'd1), res_I_V_39_fu_1047_p3[3:0]};

assign p_Result_82_fu_1153_p4 = {{x_l_I_V_41_fu_1119_p3[21:6]}};

assign p_Result_83_fu_1179_p5 = {{x_l_I_V_41_reg_1573[35:22]}, {sub_ln212_11_reg_1591}, {x_l_I_V_41_reg_1573[5:0]}};

assign p_Result_84_fu_1189_p4 = {res_I_V_40_reg_1579[17 - 1:4], |(1'd1), res_I_V_40_reg_1579[2:0]};

assign p_Result_85_fu_1228_p4 = {{x_l_I_V_42_fu_1198_p3[20:4]}};

assign p_Result_86_fu_1282_p5 = {{x_l_I_V_42_reg_1596[35:21]}, {sub_ln212_12_reg_1607}, {x_l_I_V_42_reg_1596[3:0]}};

assign p_Result_87_fu_1254_p4 = {res_I_V_41_fu_1204_p3[17 - 1:3], |(1'd1), res_I_V_41_fu_1204_p3[1:0]};

assign p_Result_88_fu_1305_p4 = {{x_l_I_V_43_fu_1292_p3[19:2]}};

assign p_Result_89_fu_1331_p5 = {{x_l_I_V_43_fu_1292_p3[35:20]}, {sub_ln212_13_fu_1325_p2}, {x_l_I_V_43_fu_1292_p3[1:0]}};

assign p_Result_8_fu_350_p4 = {{res_I_V_31_fu_342_p3[16:13]}};

assign p_Result_90_fu_1343_p4 = {res_I_V_42_reg_1612[17 - 1:2], |(1'd1), res_I_V_42_reg_1612[0:0]};

assign p_Result_91_fu_1375_p1 = x_l_I_V_44_fu_1352_p3[18:0];

assign p_Result_92_fu_1395_p5 = {{x_l_I_V_44_reg_1623[35:19]}, {sub_ln212_14_reg_1641}};

assign p_Result_93_fu_1405_p4 = {res_I_V_43_reg_1629[17-1:1], |(1'd1)};

assign p_Result_s_60_fu_1438_p2 = ((x_l_I_V_45_fu_1414_p3 > zext_ln671_fu_1434_p1) ? 1'b1 : 1'b0);

assign p_Result_s_fu_425_p4 = {{res_I_V_32_fu_419_p3[16:12]}};

assign res_I_V_29_fu_1444_p2 = (res_I_V_44_fu_1420_p3 + 17'd1);

assign res_I_V_31_fu_342_p3 = ((icmp_ln443_fu_300_p2[0:0] == 1'b1) ? select_ln239_fu_262_p3 : p_Result_51_fu_324_p4);

assign res_I_V_32_fu_419_p3 = ((icmp_ln443_1_reg_1470[0:0] == 1'b1) ? res_I_V_31_reg_1464 : p_Result_54_fu_404_p4);

assign res_I_V_33_fu_499_p3 = ((icmp_ln443_2_fu_457_p2[0:0] == 1'b1) ? res_I_V_32_fu_419_p3 : p_Result_57_fu_481_p4);

assign res_I_V_34_fu_576_p3 = ((icmp_ln443_3_reg_1493[0:0] == 1'b1) ? res_I_V_33_reg_1487 : p_Result_60_fu_561_p4);

assign res_I_V_35_fu_656_p3 = ((icmp_ln443_4_fu_614_p2[0:0] == 1'b1) ? res_I_V_34_fu_576_p3 : p_Result_63_fu_638_p4);

assign res_I_V_36_fu_813_p3 = ((icmp_ln443_6_fu_771_p2[0:0] == 1'b1) ? res_I_V_fu_733_p3 : p_Result_69_fu_795_p4);

assign res_I_V_37_fu_890_p3 = ((icmp_ln443_7_reg_1539[0:0] == 1'b1) ? res_I_V_36_reg_1533 : p_Result_72_fu_875_p4);

assign res_I_V_38_fu_970_p3 = ((icmp_ln443_8_fu_928_p2[0:0] == 1'b1) ? res_I_V_37_fu_890_p3 : p_Result_75_fu_952_p4);

assign res_I_V_39_fu_1047_p3 = ((icmp_ln443_9_reg_1562[0:0] == 1'b1) ? res_I_V_38_reg_1556 : p_Result_78_fu_1032_p4);

assign res_I_V_40_fu_1127_p3 = ((icmp_ln443_10_fu_1085_p2[0:0] == 1'b1) ? res_I_V_39_fu_1047_p3 : p_Result_81_fu_1109_p4);

assign res_I_V_41_fu_1204_p3 = ((icmp_ln443_11_reg_1585[0:0] == 1'b1) ? res_I_V_40_reg_1579 : p_Result_84_fu_1189_p4);

assign res_I_V_42_fu_1264_p3 = ((icmp_ln443_12_fu_1242_p2[0:0] == 1'b1) ? res_I_V_41_fu_1204_p3 : p_Result_87_fu_1254_p4);

assign res_I_V_43_fu_1360_p3 = ((icmp_ln443_13_fu_1319_p2[0:0] == 1'b1) ? res_I_V_42_reg_1612 : p_Result_90_fu_1343_p4);

assign res_I_V_44_fu_1420_p3 = ((icmp_ln443_14_reg_1635[0:0] == 1'b1) ? res_I_V_43_reg_1629 : p_Result_93_fu_1405_p4);

assign res_I_V_fu_733_p3 = ((icmp_ln443_5_reg_1516[0:0] == 1'b1) ? res_I_V_35_reg_1510 : p_Result_66_fu_718_p4);

assign select_ln239_fu_262_p3 = ((tmp_fu_226_p3[0:0] == 1'b1) ? 17'd32768 : 17'd0);

assign select_ln277_fu_234_p3 = ((tmp_fu_226_p3[0:0] == 1'b1) ? 4'd2 : 4'd15);

assign select_ln443_fu_270_p3 = ((tmp_fu_226_p3[0:0] == 1'b1) ? 2'd2 : 2'd0);

assign sext_ln666_fu_218_p0 = x_int_reg;

assign sext_ln666_fu_218_p1 = sext_ln666_fu_218_p0;

assign sub_ln212_10_fu_1091_p2 = (p_Result_79_fu_1071_p4 - zext_ln443_10_fu_1081_p1);

assign sub_ln212_11_fu_1173_p2 = (p_Result_82_fu_1153_p4 - zext_ln443_11_fu_1163_p1);

assign sub_ln212_12_fu_1248_p2 = (p_Result_85_fu_1228_p4 - zext_ln443_12_fu_1238_p1);

assign sub_ln212_13_fu_1325_p2 = (p_Result_88_fu_1305_p4 - zext_ln443_13_fu_1315_p1);

assign sub_ln212_14_fu_1389_p2 = (p_Result_91_fu_1375_p1 - zext_ln443_14_fu_1379_p1);

assign sub_ln212_1_fu_388_p2 = (p_Result_52_fu_368_p4 - zext_ln443_1_fu_378_p1);

assign sub_ln212_2_fu_463_p2 = (p_Result_55_fu_443_p4 - zext_ln443_2_fu_453_p1);

assign sub_ln212_3_fu_545_p2 = (p_Result_58_fu_525_p4 - zext_ln443_3_fu_535_p1);

assign sub_ln212_4_fu_620_p2 = (p_Result_61_fu_600_p4 - zext_ln443_4_fu_610_p1);

assign sub_ln212_5_fu_702_p2 = (p_Result_64_fu_682_p4 - zext_ln443_5_fu_692_p1);

assign sub_ln212_6_fu_777_p2 = (p_Result_67_fu_757_p4 - zext_ln443_6_fu_767_p1);

assign sub_ln212_7_fu_859_p2 = (p_Result_70_fu_839_p4 - zext_ln443_7_fu_849_p1);

assign sub_ln212_8_fu_934_p2 = (p_Result_73_fu_914_p4 - zext_ln443_8_fu_924_p1);

assign sub_ln212_9_fu_1016_p2 = (p_Result_76_fu_996_p4 - zext_ln443_9_fu_1006_p1);

assign sub_ln212_fu_306_p2 = (p_Result_49_fu_286_p4 - zext_ln443_fu_296_p1);

assign tmp_10_fu_1063_p3 = {{p_Result_30_fu_1053_p4}, {1'd1}};

assign tmp_11_fu_1145_p3 = {{p_Result_33_fu_1135_p4}, {1'd1}};

assign tmp_12_fu_1220_p3 = {{p_Result_36_fu_1210_p4}, {1'd1}};

assign tmp_13_fu_1298_p3 = {{p_Result_39_reg_1618}, {1'd1}};

assign tmp_14_fu_1367_p3 = {{res_I_V_43_fu_1360_p3}, {1'd1}};

assign tmp_1_fu_988_p3 = {{p_Result_27_fu_978_p4}, {1'd1}};

assign tmp_2_fu_278_p3 = {{select_ln443_fu_270_p3}, {1'd1}};

assign tmp_3_fu_360_p3 = {{p_Result_8_fu_350_p4}, {1'd1}};

assign tmp_4_fu_435_p3 = {{p_Result_s_fu_425_p4}, {1'd1}};

assign tmp_5_fu_517_p3 = {{p_Result_5_fu_507_p4}, {1'd1}};

assign tmp_6_fu_592_p3 = {{p_Result_10_fu_582_p4}, {1'd1}};

assign tmp_7_fu_674_p3 = {{p_Result_14_fu_664_p4}, {1'd1}};

assign tmp_8_fu_749_p3 = {{p_Result_18_fu_739_p4}, {1'd1}};

assign tmp_9_fu_831_p3 = {{p_Result_21_fu_821_p4}, {1'd1}};

assign tmp_fu_226_p1 = x_int_reg;

assign tmp_fu_226_p3 = tmp_fu_226_p1[32'd26];

assign tmp_s_fu_906_p3 = {{p_Result_24_fu_896_p4}, {1'd1}};

assign x_l_I_V_31_fu_254_p3 = ((tmp_fu_226_p3[0:0] == 1'b1) ? p_Result_48_fu_242_p5 : zext_ln666_fu_222_p1);

assign x_l_I_V_32_fu_334_p3 = ((icmp_ln443_fu_300_p2[0:0] == 1'b1) ? x_l_I_V_31_fu_254_p3 : p_Result_50_fu_312_p5);

assign x_l_I_V_33_fu_413_p3 = ((icmp_ln443_1_reg_1470[0:0] == 1'b1) ? x_l_I_V_32_reg_1458 : p_Result_53_fu_394_p5);

assign x_l_I_V_34_fu_491_p3 = ((icmp_ln443_2_fu_457_p2[0:0] == 1'b1) ? x_l_I_V_33_fu_413_p3 : p_Result_56_fu_469_p5);

assign x_l_I_V_35_fu_570_p3 = ((icmp_ln443_3_reg_1493[0:0] == 1'b1) ? x_l_I_V_34_reg_1481 : p_Result_59_fu_551_p5);

assign x_l_I_V_36_fu_727_p3 = ((icmp_ln443_5_reg_1516[0:0] == 1'b1) ? x_l_I_V_reg_1504 : p_Result_65_fu_708_p5);

assign x_l_I_V_37_fu_805_p3 = ((icmp_ln443_6_fu_771_p2[0:0] == 1'b1) ? x_l_I_V_36_fu_727_p3 : p_Result_68_fu_783_p5);

assign x_l_I_V_38_fu_884_p3 = ((icmp_ln443_7_reg_1539[0:0] == 1'b1) ? x_l_I_V_37_reg_1527 : p_Result_71_fu_865_p5);

assign x_l_I_V_39_fu_962_p3 = ((icmp_ln443_8_fu_928_p2[0:0] == 1'b1) ? x_l_I_V_38_fu_884_p3 : p_Result_74_fu_940_p5);

assign x_l_I_V_40_fu_1041_p3 = ((icmp_ln443_9_reg_1562[0:0] == 1'b1) ? x_l_I_V_39_reg_1550 : p_Result_77_fu_1022_p5);

assign x_l_I_V_41_fu_1119_p3 = ((icmp_ln443_10_fu_1085_p2[0:0] == 1'b1) ? x_l_I_V_40_fu_1041_p3 : p_Result_80_fu_1097_p5);

assign x_l_I_V_42_fu_1198_p3 = ((icmp_ln443_11_reg_1585[0:0] == 1'b1) ? x_l_I_V_41_reg_1573 : p_Result_83_fu_1179_p5);

assign x_l_I_V_43_fu_1292_p3 = ((icmp_ln443_12_reg_1602[0:0] == 1'b1) ? x_l_I_V_42_reg_1596 : p_Result_86_fu_1282_p5);

assign x_l_I_V_44_fu_1352_p3 = ((icmp_ln443_13_fu_1319_p2[0:0] == 1'b1) ? x_l_I_V_43_fu_1292_p3 : p_Result_89_fu_1331_p5);

assign x_l_I_V_45_fu_1414_p3 = ((icmp_ln443_14_reg_1635[0:0] == 1'b1) ? x_l_I_V_44_reg_1623 : p_Result_92_fu_1395_p5);

assign x_l_I_V_fu_648_p3 = ((icmp_ln443_4_fu_614_p2[0:0] == 1'b1) ? x_l_I_V_35_fu_570_p3 : p_Result_62_fu_626_p5);

assign zext_ln443_10_fu_1081_p1 = tmp_10_fu_1063_p3;

assign zext_ln443_11_fu_1163_p1 = tmp_11_fu_1145_p3;

assign zext_ln443_12_fu_1238_p1 = tmp_12_fu_1220_p3;

assign zext_ln443_13_fu_1315_p1 = tmp_13_fu_1298_p3;

assign zext_ln443_14_fu_1379_p1 = tmp_14_fu_1367_p3;

assign zext_ln443_1_fu_378_p1 = tmp_3_fu_360_p3;

assign zext_ln443_2_fu_453_p1 = tmp_4_fu_435_p3;

assign zext_ln443_3_fu_535_p1 = tmp_5_fu_517_p3;

assign zext_ln443_4_fu_610_p1 = tmp_6_fu_592_p3;

assign zext_ln443_5_fu_692_p1 = tmp_7_fu_674_p3;

assign zext_ln443_6_fu_767_p1 = tmp_8_fu_749_p3;

assign zext_ln443_7_fu_849_p1 = tmp_9_fu_831_p3;

assign zext_ln443_8_fu_924_p1 = tmp_s_fu_906_p3;

assign zext_ln443_9_fu_1006_p1 = tmp_1_fu_988_p3;

assign zext_ln443_fu_296_p1 = tmp_2_fu_278_p3;

assign zext_ln666_fu_222_p1 = $unsigned(sext_ln666_fu_218_p1);

assign zext_ln671_fu_1434_p1 = mul_I_V_fu_1426_p3;

endmodule //eucDis_sqrt_fixed_33_33_s
